

source "https://rubygems.org"

gem "net-smtp", "~> 0.5.1"
gem "pony",     "~> 1.13"
gem "puma",     "~> 8.0"
gem "sinatra",  "~> 4.2"
gem "rackup",   "~> 2.3"

gem "google-protobuf", "~> 4.35.0"

gem "opentelemetry-sdk",                 "~> 1.12"
gem "opentelemetry-exporter-otlp",       "~> 0.34.0"
gem "opentelemetry-instrumentation-all", "~> 0.94.0"
